import type {
  FileIdentity,
  RelPath,
  RealPath,
  RestoreResultKind,
  Sha256Hex,
  SymlinkInfo,
  Timestamp,
} from './common.js';

/** Artifact classification kinds (R1). */
export type ArtifactKind = 'temp' | 'intermediate' | 'cache' | 'build' | 'generated' | 'unknown';

/** How a candidate was attributed to the current task (R1). */
export type Provenance = 'baseline_diff' | 'task_write' | 'git_untracked' | 'declared' | 'unknown';

/** Candidate/artifact lifecycle state (R1). */
export type ArtifactState =
  | 'candidate'
  | 'planned_keep'
  | 'planned_quarantine'
  | 'quarantined'
  | 'restored'
  | 'expired'
  | 'purged'
  | 'skipped';

/**
 * ArtifactCandidate: a task artifact recognized for cleanup.
 *
 * Mirrors the `artifact` entry of `specs/v1alpha1/cleanup-manifest.schema.json`.
 * `decisionId` is always produced by the SafetyKernel (S-06); it is never
 * generated by the data layer.
 */
export interface ArtifactCandidate {
  readonly artifactId: string;
  readonly candidateId: string;
  readonly decisionId: string;
  readonly relPath: RelPath;
  readonly sourceRealPath?: RealPath;
  readonly kind: ArtifactKind;
  readonly provenance: Provenance;
  readonly identity: FileIdentity;
  readonly sizeBytes: number;
  readonly sha256: Sha256Hex;
  readonly mtime: Timestamp;
  readonly mode: string;
  readonly gitTracked: boolean;
  readonly symlink: SymlinkInfo | null;
  readonly matchedBy: readonly string[];
  readonly state: ArtifactState;
}

export type PlanStatus = 'draft' | 'frozen' | 'applied' | 'closed' | 'superseded';

/**
 * CleanupPlan: a safety decision applied over a manifest's candidates.
 */
export interface CleanupPlan {
  readonly planId: string;
  readonly manifestId: string;
  readonly taskId: string;
  readonly runId: string;
  readonly createdAt: Timestamp;
  readonly status: PlanStatus;
  readonly candidates: readonly ArtifactCandidate[];
}

export interface RestoreEntryFailure {
  readonly entryId: string;
  readonly candidateId: string;
  readonly reason: string;
}

/**
 * RestoreResult: outcome of restoring a quarantined batch.
 */
export interface RestoreResult {
  readonly restoreId: string;
  readonly quarantineId: string;
  readonly decisionId: string;
  readonly requestedBy: string;
  readonly requestedAt: Timestamp;
  readonly result: RestoreResultKind;
  readonly failures: readonly RestoreEntryFailure[];
}
